"""Curated AI news sources used by the scraper layer."""

from __future__ import annotations

from .models import NewsSource


SOURCES: tuple[NewsSource, ...] = (
    NewsSource("OpenAI News", "https://openai.com/news/", "official", "https://openai.com/news/rss.xml"),
    NewsSource("OpenAI Blog", "https://openai.com/blog/", "official", "https://openai.com/news/rss.xml"),
    NewsSource("Anthropic News", "https://www.anthropic.com/news", "official", "https://www.anthropic.com/news/rss.xml"),
    NewsSource("Google DeepMind News", "https://deepmind.google/blog/", "official", "https://deepmind.google/blog/rss.xml"),
    NewsSource("Google AI Blog", "https://ai.googleblog.com/", "official", "https://ai.googleblog.com/feeds/posts/default"),
    NewsSource("Google Cloud AI Blog", "https://cloud.google.com/blog/products/ai-machine-learning", "official", "https://cloudblog.withgoogle.com/products/ai-machine-learning/rss/"),
    NewsSource("Meta AI Blog", "https://ai.meta.com/blog/", "official"),
    NewsSource("Microsoft AI Blog", "https://blogs.microsoft.com/ai/", "official", "https://blogs.microsoft.com/ai/feed/"),
    NewsSource("Microsoft Research AI", "https://www.microsoft.com/en-us/research/research-area/artificial-intelligence/", "official"),
    NewsSource("NVIDIA AI Blog", "https://blogs.nvidia.com/blog/category/deep-learning/", "official", "https://blogs.nvidia.com/blog/category/deep-learning/feed/"),
    NewsSource("Mistral AI News", "https://mistral.ai/news/", "official"),
    NewsSource("xAI News", "https://x.ai/news", "official"),
    NewsSource("Hugging Face Blog", "https://huggingface.co/blog", "official", "https://huggingface.co/blog/feed.xml"),
    NewsSource("Stability AI News", "https://stability.ai/news", "official"),
    NewsSource("Cohere Blog", "https://cohere.com/blog", "official"),
    NewsSource("Perplexity Blog", "https://www.perplexity.ai/hub/blog", "official"),
    NewsSource("AWS Machine Learning Blog", "https://aws.amazon.com/blogs/machine-learning/", "official", "https://aws.amazon.com/blogs/machine-learning/feed/"),
    NewsSource("Apple Machine Learning Research", "https://machinelearning.apple.com/", "official"),
    NewsSource("TechCrunch AI", "https://techcrunch.com/category/artificial-intelligence/", "media", "https://techcrunch.com/category/artificial-intelligence/feed/"),
    NewsSource("The Verge AI", "https://www.theverge.com/ai-artificial-intelligence", "media", "https://www.theverge.com/rss/ai-artificial-intelligence/index.xml"),
    NewsSource("VentureBeat AI", "https://venturebeat.com/category/ai/", "media", "https://venturebeat.com/category/ai/feed/"),
    NewsSource("MIT Technology Review AI", "https://www.technologyreview.com/topic/artificial-intelligence/", "media", "https://www.technologyreview.com/feed/"),
    NewsSource("WIRED AI", "https://www.wired.com/tag/artificial-intelligence/", "media", "https://www.wired.com/feed/tag/ai/latest/rss"),
    NewsSource("Ars Technica AI", "https://arstechnica.com/tag/artificial-intelligence/", "media", "https://arstechnica.com/tag/artificial-intelligence/feed/"),
    NewsSource("Axios AI", "https://www.axios.com/technology/artificial-intelligence", "media"),
    NewsSource("Reuters AI", "https://www.reuters.com/technology/artificial-intelligence/", "media"),
    NewsSource("Bloomberg AI", "https://www.bloomberg.com/artificial-intelligence", "media"),
    NewsSource("CNBC AI", "https://www.cnbc.com/artificial-intelligence/", "media", "https://www.cnbc.com/id/100727362/device/rss/rss.html"),
    NewsSource("The Decoder", "https://the-decoder.com/", "media", "https://the-decoder.com/feed/"),
    NewsSource("Unite.AI", "https://www.unite.ai/", "media", "https://www.unite.ai/feed/"),
    NewsSource("AI News", "https://www.artificialintelligence-news.com/", "media", "https://www.artificialintelligence-news.com/feed/"),
    NewsSource("AI Business", "https://aibusiness.com/", "media", "https://aibusiness.com/rss.xml"),
    NewsSource("InfoQ AI ML Data Engineering", "https://www.infoq.com/ai-ml-data-eng/", "media", "https://feed.infoq.com/ai-ml-data-eng/"),
    NewsSource("KDnuggets", "https://www.kdnuggets.com/", "media", "https://www.kdnuggets.com/feed"),
    NewsSource("Analytics Vidhya", "https://www.analyticsvidhya.com/blog/", "media", "https://www.analyticsvidhya.com/feed/"),
    NewsSource("Towards Data Science", "https://towardsdatascience.com/", "media", "https://towardsdatascience.com/feed"),
    NewsSource("MarkTechPost", "https://www.marktechpost.com/", "media", "https://www.marktechpost.com/feed/"),
    NewsSource("Synced", "https://syncedreview.com/", "media", "https://syncedreview.com/feed/"),
    NewsSource("arXiv Artificial Intelligence", "https://arxiv.org/list/cs.AI/recent", "research", "https://export.arxiv.org/rss/cs.AI"),
    NewsSource("arXiv Machine Learning", "https://arxiv.org/list/cs.LG/recent", "research", "https://export.arxiv.org/rss/cs.LG"),
    NewsSource("arXiv Computation and Language", "https://arxiv.org/list/cs.CL/recent", "research", "https://export.arxiv.org/rss/cs.CL"),
    NewsSource("Papers with Code", "https://paperswithcode.com/", "research"),
    NewsSource("Hugging Face Papers", "https://huggingface.co/papers", "research", "https://huggingface.co/papers/rss.xml"),
    NewsSource("LMSYS Chatbot Arena", "https://lmarena.ai/", "research"),
    NewsSource("Stanford HAI News", "https://hai.stanford.edu/news", "research", "https://hai.stanford.edu/news/rss.xml"),
    NewsSource("Berkeley AI Research Blog", "https://bair.berkeley.edu/blog/", "research", "https://bair.berkeley.edu/blog/feed.xml"),
    NewsSource("MIT CSAIL News", "https://www.csail.mit.edu/news", "research", "https://www.csail.mit.edu/rss.xml"),
    NewsSource("The Gradient", "https://thegradient.pub/", "research", "https://thegradient.pub/rss/"),
    NewsSource("Distill", "https://distill.pub/", "research", "https://distill.pub/rss.xml"),
    NewsSource("Google Research Blog", "https://research.google/blog/", "research", "https://research.google/blog/rss/"),
    NewsSource("Allen Institute for AI Blog", "https://allenai.org/blog", "research", "https://allenai.org/blog/rss.xml"),
    NewsSource("The Batch", "https://www.deeplearning.ai/the-batch/", "newsletter", "https://www.deeplearning.ai/the-batch/feed/"),
    NewsSource("Import AI", "https://jack-clark.net/", "newsletter", "https://jack-clark.net/feed/"),
    NewsSource("Last Week in AI", "https://lastweekin.ai/", "newsletter", "https://lastweekin.ai/feed/"),
    NewsSource("Ben's Bites", "https://www.bensbites.co/", "newsletter"),
    NewsSource("TLDR AI", "https://tldr.tech/ai", "newsletter"),
    NewsSource("Superhuman AI", "https://www.superhuman.ai/", "newsletter"),
    NewsSource("Future Tools AI News", "https://futuretools.io/news", "newsletter"),
    NewsSource("AI Roundup", "https://www.ai-roundup.dev/", "newsletter"),
    NewsSource("TalkAIToday", "https://talkaitoday.com/", "newsletter", "https://talkaitoday.com/feed/"),
    NewsSource("TheOutpost.AI", "https://theoutpost.ai/", "newsletter"),
    NewsSource("AI Agentic News", "https://aiagentic.news/", "newsletter"),
    NewsSource("NIST AI", "https://www.nist.gov/artificial-intelligence", "policy"),
    NewsSource("OECD AI Policy Observatory", "https://oecd.ai/", "policy"),
    NewsSource("AI Now Institute", "https://ainowinstitute.org/", "policy", "https://ainowinstitute.org/feed"),
    NewsSource("Future of Life Institute AI", "https://futureoflife.org/artificial-intelligence/", "policy", "https://futureoflife.org/feed/"),
    NewsSource("Center for AI Safety", "https://www.safe.ai/", "policy"),
    NewsSource("Partnership on AI", "https://partnershiponai.org/", "policy", "https://partnershiponai.org/feed/"),
    NewsSource("EFF AI", "https://www.eff.org/issues/ai", "policy", "https://www.eff.org/rss/updates.xml"),
    NewsSource("Brookings AI", "https://www.brookings.edu/topic/artificial-intelligence/", "policy", "https://www.brookings.edu/topic/artificial-intelligence/feed/"),
    NewsSource("RAND AI", "https://www.rand.org/topics/artificial-intelligence.html", "policy"),
)


def sources_by_category(category: str) -> tuple[NewsSource, ...]:
    """Return all configured sources in a category."""

    return tuple(source for source in SOURCES if source.category == category)
