"""Curated AI news sources used by the scraper layer."""

from __future__ import annotations

from .models import NewsSource


SOURCES: tuple[NewsSource, ...] = (
    NewsSource("OpenAI News", "https://openai.com/news/", "official", "https://openai.com/news/rss.xml"),
    NewsSource("OpenAI Blog", "https://openai.com/blog/", "official", "https://openai.com/news/rss.xml"),
    NewsSource("Anthropic News", "https://www.anthropic.com/news", "official", "https://www.anthropic.com/news/rss.xml"),
    NewsSource("Google DeepMind News", "https://deepmind.google/blog/", "official", "https://deepmind.google/blog/rss.xml"),
    NewsSource("Google AI Blog", "https://ai.googleblog.com/", "official", "https://ai.googleblog.com/feeds/posts/default"),
    NewsSource("Google Cloud AI Blog", "https://cloud.google.com/blog/products/ai-machine-learning", "official", "https://cloudblog.withgoogle.com/products/ai-machine-learning/rss/"),
    NewsSource("Meta AI Blog", "https://ai.meta.com/blog/", "official"),
    NewsSource("Microsoft AI Blog", "https://blogs.microsoft.com/ai/", "official", "https://blogs.microsoft.com/ai/feed/"),
    NewsSource("Microsoft Research AI", "https://www.microsoft.com/en-us/research/research-area/artificial-intelligence/", "official"),
    NewsSource("NVIDIA AI Blog", "https://blogs.nvidia.com/blog/category/deep-learning/", "official", "https://blogs.nvidia.com/blog/category/deep-learning/feed/"),
    NewsSource("Mistral AI News", "https://mistral.ai/news/", "official"),
    NewsSource("xAI News", "https://x.ai/news", "official"),
    NewsSource("Hugging Face Blog", "https://huggingface.co/blog", "official", "https://huggingface.co/blog/feed.xml"),
    NewsSource("Stability AI News", "https://stability.ai/news", "official"),
    NewsSource("Cohere Blog", "https://cohere.com/blog", "official"),
    NewsSource("Perplexity Blog", "https://www.perplexity.ai/hub/blog", "official"),
    NewsSource("AWS Machine Learning Blog", "https://aws.amazon.com/blogs/machine-learning/", "official", "https://aws.amazon.com/blogs/machine-learning/feed/"),
    NewsSource("Apple Machine Learning Research", "https://machinelearning.apple.com/", "official", "https://machinelearning.apple.com/rss.xml"),
    NewsSource("TechCrunch AI", "https://techcrunch.com/category/artificial-intelligence/", "media", "https://techcrunch.com/category/artificial-intelligence/feed/"),
    NewsSource("The Verge AI", "https://www.theverge.com/ai-artificial-intelligence", "media", "https://www.theverge.com/rss/ai-artificial-intelligence/index.xml"),
    NewsSource("VentureBeat AI", "https://venturebeat.com/category/ai/", "media", "https://venturebeat.com/category/ai/feed/"),
    NewsSource("MIT Technology Review AI", "https://www.technologyreview.com/topic/artificial-intelligence/", "media", "https://www.technologyreview.com/feed/"),
    NewsSource("WIRED AI", "https://www.wired.com/tag/artificial-intelligence/", "media", "https://www.wired.com/feed/tag/ai/latest/rss"),
    NewsSource("Ars Technica AI", "https://arstechnica.com/tag/artificial-intelligence/", "media", "https://arstechnica.com/tag/artificial-intelligence/feed/"),
    NewsSource("Axios AI", "https://www.axios.com/technology/artificial-intelligence", "media", "https://www.axios.com/feeds/feed.rss"),
    NewsSource("CNBC AI", "https://www.cnbc.com/artificial-intelligence/", "media", "https://www.cnbc.com/id/100727362/device/rss/rss.html"),
    NewsSource("The Decoder", "https://the-decoder.com/", "media", "https://the-decoder.com/feed/"),
    NewsSource("Unite.AI", "https://www.unite.ai/", "media", "https://www.unite.ai/feed/"),
    NewsSource("AI News", "https://www.artificialintelligence-news.com/", "media", "https://www.artificialintelligence-news.com/feed/"),
    NewsSource("AI Business", "https://aibusiness.com/", "media", "https://aibusiness.com/rss.xml"),
    NewsSource("InfoQ AI ML Data Engineering", "https://www.infoq.com/ai-ml-data-eng/", "media", "https://feed.infoq.com/ai-ml-data-eng/"),
    NewsSource("KDnuggets", "https://www.kdnuggets.com/", "media", "https://www.kdnuggets.com/feed"),
    NewsSource("Analytics Vidhya", "https://www.analyticsvidhya.com/blog/", "media", "https://www.analyticsvidhya.com/feed/"),
    NewsSource("Towards Data Science", "https://towardsdatascience.com/", "media", "https://towardsdatascience.com/feed"),
    NewsSource("MarkTechPost", "https://www.marktechpost.com/", "media", "https://www.marktechpost.com/feed/"),
    NewsSource("Synced", "https://syncedreview.com/", "media", "https://syncedreview.com/feed/"),
    NewsSource("arXiv Artificial Intelligence", "https://arxiv.org/list/cs.AI/recent", "research", "https://export.arxiv.org/rss/cs.AI"),
    NewsSource("arXiv Machine Learning", "https://arxiv.org/list/cs.LG/recent", "research", "https://export.arxiv.org/rss/cs.LG"),
    NewsSource("arXiv Computation and Language", "https://arxiv.org/list/cs.CL/recent", "research", "https://export.arxiv.org/rss/cs.CL"),
    NewsSource("Papers with Code", "https://paperswithcode.com/", "research"),
    NewsSource("Hugging Face Papers", "https://huggingface.co/papers", "research", "https://huggingface.co/papers/rss.xml"),
    NewsSource("Stanford HAI News", "https://hai.stanford.edu/news", "research", "https://hai.stanford.edu/news/rss.xml"),
    NewsSource("Berkeley AI Research Blog", "https://bair.berkeley.edu/blog/", "research", "https://bair.berkeley.edu/blog/feed.xml"),
    NewsSource("MIT CSAIL News", "https://www.csail.mit.edu/news", "research", "https://www.csail.mit.edu/rss.xml"),
    NewsSource("The Gradient", "https://thegradient.pub/", "research", "https://thegradient.pub/rss/"),
    NewsSource("Distill", "https://distill.pub/", "research", "https://distill.pub/rss.xml"),
    NewsSource("Google Research Blog", "https://research.google/blog/", "research", "https://research.google/blog/rss/"),
    NewsSource("Allen Institute for AI Blog", "https://allenai.org/blog", "research", "https://allenai.org/blog/rss.xml"),
    NewsSource("The Batch", "https://www.deeplearning.ai/the-batch/", "newsletter", "https://www.deeplearning.ai/the-batch/feed/"),
    NewsSource("Import AI", "https://jack-clark.net/", "newsletter", "https://jack-clark.net/feed/"),
    NewsSource("Last Week in AI", "https://lastweekin.ai/", "newsletter", "https://lastweekin.ai/feed/"),
    NewsSource("Ben's Bites", "https://www.bensbites.co/", "newsletter"),
    NewsSource("TLDR AI", "https://tldr.tech/ai", "newsletter"),
    NewsSource("Future Tools AI News", "https://futuretools.io/news", "newsletter"),
    NewsSource("AI Roundup", "https://www.ai-roundup.dev/", "newsletter"),
    NewsSource("TheOutpost.AI", "https://theoutpost.ai/", "newsletter"),
    NewsSource("AI Agentic News", "https://aiagentic.news/", "newsletter"),
    NewsSource("NIST AI", "https://www.nist.gov/artificial-intelligence", "policy"),
    NewsSource("OECD AI Policy Observatory", "https://oecd.ai/", "policy"),
    NewsSource("AI Now Institute", "https://ainowinstitute.org/", "policy", "https://ainowinstitute.org/feed"),
    NewsSource("Future of Life Institute AI", "https://futureoflife.org/artificial-intelligence/", "policy", "https://futureoflife.org/feed/"),
    NewsSource("Center for AI Safety", "https://www.safe.ai/", "policy"),
    NewsSource("Partnership on AI", "https://partnershiponai.org/", "policy", "https://partnershiponai.org/feed/"),
    NewsSource("EFF AI", "https://www.eff.org/issues/ai", "policy", "https://www.eff.org/rss/updates.xml"),
    NewsSource("Brookings AI", "https://www.brookings.edu/topic/artificial-intelligence/", "policy", "https://www.brookings.edu/topic/artificial-intelligence/feed/"),
    NewsSource("Google AI Developers Blog", "https://developers.googleblog.com/search/label/AI", "official", "https://developers.googleblog.com/feeds/posts/default/-/AI"),
    NewsSource("Google Cloud Generative AI", "https://cloud.google.com/blog/topics/generative-ai", "official", "https://cloudblog.withgoogle.com/topics/generative-ai/rss/"),
    NewsSource("Microsoft Azure AI Blog", "https://azure.microsoft.com/en-us/blog/topics/ai-machine-learning/", "official", "https://azure.microsoft.com/en-us/blog/feed/"),
    NewsSource("Microsoft Semantic Kernel Blog", "https://devblogs.microsoft.com/semantic-kernel/", "official", "https://devblogs.microsoft.com/semantic-kernel/feed/"),
    NewsSource("GitHub Blog AI", "https://github.blog/tag/ai/", "official", "https://github.blog/tag/ai/feed/"),
    NewsSource("GitHub Copilot Blog", "https://github.blog/tag/github-copilot/", "official", "https://github.blog/tag/github-copilot/feed/"),
    NewsSource("NVIDIA Technical Blog AI", "https://developer.nvidia.com/blog/category/deep-learning/", "official", "https://developer.nvidia.com/blog/category/deep-learning/feed/"),
    NewsSource("NVIDIA Generative AI", "https://developer.nvidia.com/blog/category/generative-ai/", "official", "https://developer.nvidia.com/blog/category/generative-ai/feed/"),
    NewsSource("IBM AI Blog", "https://www.ibm.com/blog/category/artificial-intelligence/", "official", "https://www.ibm.com/blog/category/artificial-intelligence/feed/"),
    NewsSource("Salesforce AI Blog", "https://www.salesforce.com/blog/category/artificial-intelligence/", "official"),
    NewsSource("Salesforce Engineering AI", "https://engineering.salesforce.com/tag/ai/", "official", "https://engineering.salesforce.com/tag/ai/feed/"),
    NewsSource("Adobe AI News", "https://news.adobe.com/news/ai", "official"),
    NewsSource("Oracle AI", "https://www.oracle.com/artificial-intelligence/", "official"),
    NewsSource("Databricks Blog AI", "https://www.databricks.com/blog/category/solutions/ai-and-machine-learning", "official"),
    NewsSource("Snowflake Blog AI", "https://www.snowflake.com/blog/category/generative-ai/", "official"),
    NewsSource("MongoDB AI Blog", "https://www.mongodb.com/blog/channel/ai", "official"),
    NewsSource("Cloudflare AI Blog", "https://blog.cloudflare.com/tag/ai/", "official", "https://blog.cloudflare.com/tag/ai/rss/"),
    NewsSource("Vercel AI Blog", "https://vercel.com/blog/category/ai", "official"),
    NewsSource("Replit Blog AI", "https://blog.replit.com/tag/ai", "official"),
    NewsSource("Cursor Blog", "https://www.cursor.com/blog", "official"),
    NewsSource("LangChain Blog", "https://blog.langchain.com/", "official", "https://blog.langchain.com/rss/"),
    NewsSource("LangGraph Blog", "https://blog.langchain.com/tag/langgraph/", "official", "https://blog.langchain.com/tag/langgraph/rss/"),
    NewsSource("LlamaIndex Blog", "https://www.llamaindex.ai/blog", "official"),
    NewsSource("Weights & Biases Blog", "https://wandb.ai/site/articles", "official"),
    NewsSource("Modal Blog", "https://modal.com/blog", "official"),
    NewsSource("Replicate Blog", "https://replicate.com/blog", "official"),
    NewsSource("Pinecone Blog", "https://www.pinecone.io/blog/", "official", "https://www.pinecone.io/blog/rss.xml"),
    NewsSource("Weaviate Blog", "https://weaviate.io/blog", "official"),
    NewsSource("Qdrant Blog", "https://qdrant.tech/blog/", "official", "https://qdrant.tech/blog/rss.xml"),
    NewsSource("Chroma Blog", "https://www.trychroma.com/blog", "official"),
    NewsSource("Milvus Blog", "https://milvus.io/blog", "official"),
    NewsSource("Haystack Blog", "https://haystack.deepset.ai/blog", "official"),
    NewsSource("Together AI Blog", "https://www.together.ai/blog", "official"),
    NewsSource("Fireworks AI Blog", "https://fireworks.ai/blog", "official"),
    NewsSource("Groq Blog", "https://groq.com/blog/", "official"),
    NewsSource("Cerebras Blog", "https://www.cerebras.ai/blog", "official"),
    NewsSource("SambaNova Blog", "https://sambanova.ai/blog", "official"),
    NewsSource("Runway Blog", "https://runwayml.com/research", "official"),
    NewsSource("Midjourney Updates", "https://updates.midjourney.com/", "official"),
    NewsSource("ElevenLabs Blog", "https://elevenlabs.io/blog", "official"),
    NewsSource("AssemblyAI Blog", "https://www.assemblyai.com/blog/", "official", "https://www.assemblyai.com/blog/rss.xml"),
    NewsSource("Deepgram Blog", "https://deepgram.com/learn", "official"),
    NewsSource("OpenRouter Blog", "https://openrouter.ai/blog", "official"),
    NewsSource("Anyscale Blog", "https://www.anyscale.com/blog", "official"),
    NewsSource("DataStax AI Blog", "https://www.datastax.com/blog?field_topic_target_id=2321", "official"),
    NewsSource("Elastic AI Search Blog", "https://www.elastic.co/search-labs", "official"),
    NewsSource("Neo4j GraphRAG Blog", "https://neo4j.com/developer-blog/tag/graphrag/", "official"),
    NewsSource("Mendable Blog", "https://www.mendable.ai/blog", "official"),
    NewsSource("AgentOps Blog", "https://www.agentops.ai/blog", "official"),
    NewsSource("CrewAI Blog", "https://www.crewai.com/blog", "official"),
    NewsSource("AutoGen Blog", "https://microsoft.github.io/autogen/blog/", "official"),
    NewsSource("DSPy Blog", "https://dspy.ai/", "official"),
    NewsSource("Scale AI Blog", "https://scale.com/blog", "official"),
    NewsSource("Snorkel AI Blog", "https://snorkel.ai/blog/", "official"),
    NewsSource("Latent Space", "https://www.latent.space/", "newsletter", "https://www.latent.space/feed"),
    NewsSource("The Sequence", "https://thesequence.substack.com/", "newsletter", "https://thesequence.substack.com/feed"),
    NewsSource("Ahead of AI", "https://magazine.sebastianraschka.com/", "newsletter", "https://magazine.sebastianraschka.com/feed"),
    NewsSource("Interconnects", "https://www.interconnects.ai/", "newsletter", "https://www.interconnects.ai/feed"),
    NewsSource("Gradient Flow", "https://gradientflow.com/", "newsletter", "https://gradientflow.com/feed/"),
    NewsSource("Stanford CRFM Blog", "https://crfm.stanford.edu/blog.html", "research"),
    NewsSource("Stanford AI Lab Blog", "https://ai.stanford.edu/blog/", "research"),
    NewsSource("MIT News AI", "https://news.mit.edu/topic/artificial-intelligence2", "research", "https://news.mit.edu/rss/topic/artificial-intelligence2"),
    NewsSource("CMU Machine Learning Blog", "https://blog.ml.cmu.edu/", "research", "https://blog.ml.cmu.edu/feed/"),
    NewsSource("NVIDIA Research", "https://research.nvidia.com/labs/", "research"),
    NewsSource("Meta Research Blog", "https://research.facebook.com/blog/", "research"),
    NewsSource("OpenReview Blog", "https://blog.openreview.net/", "research"),
    NewsSource("ML Collective Blog", "https://mlcollective.org/blog/", "research"),
    NewsSource("Hazy Research Blog", "https://hazyresearch.stanford.edu/blog", "research"),
    NewsSource("Epoch AI Blog", "https://epoch.ai/blog", "research", "https://epoch.ai/blog/rss.xml"),
    NewsSource("Our World in Data AI", "https://ourworldindata.org/artificial-intelligence", "research"),
    NewsSource("Nature Machine Intelligence", "https://www.nature.com/natmachintell/", "research", "https://www.nature.com/natmachintell.rss"),
    NewsSource("IEEE Spectrum AI", "https://spectrum.ieee.org/artificial-intelligence", "media", "https://spectrum.ieee.org/feeds/topic/artificial-intelligence.rss"),
    NewsSource("Reuters AI", "https://www.reuters.com/technology/artificial-intelligence/", "media"),
    NewsSource("AP Technology AI", "https://apnews.com/hub/artificial-intelligence", "media"),
    NewsSource("Financial Times AI", "https://www.ft.com/artificial-intelligence", "media"),
    NewsSource("Fortune AI", "https://fortune.com/tag/artificial-intelligence/", "media"),
    NewsSource("Fast Company AI", "https://www.fastcompany.com/section/artificial-intelligence", "media"),
    NewsSource("ZDNET AI", "https://www.zdnet.com/topic/artificial-intelligence/", "media", "https://www.zdnet.com/topic/artificial-intelligence/rss.xml"),
    NewsSource("The Register AI", "https://www.theregister.com/software/ai_ml/", "media", "https://www.theregister.com/software/ai_ml/headlines.atom"),
    NewsSource("SiliconANGLE AI", "https://siliconangle.com/category/ai/", "media", "https://siliconangle.com/category/ai/feed/"),
    NewsSource("SD Times AI", "https://sdtimes.com/tag/artificial-intelligence/", "media", "https://sdtimes.com/tag/artificial-intelligence/feed/"),
    NewsSource("Datanami AI", "https://www.datanami.com/tag/artificial-intelligence/", "media", "https://www.datanami.com/tag/artificial-intelligence/feed/"),
    NewsSource("Dark Reading AI", "https://www.darkreading.com/artificial-intelligence", "security"),
    NewsSource("Google Security AI", "https://security.googleblog.com/search/label/AI", "security"),
    NewsSource("Microsoft Security AI", "https://www.microsoft.com/en-us/security/blog/topic/ai/", "security"),
    NewsSource("OpenSSF AI", "https://openssf.org/blog/", "security", "https://openssf.org/feed/"),
    NewsSource("OWASP AI Exchange", "https://owaspai.org/", "security"),
    NewsSource("Trail of Bits AI", "https://blog.trailofbits.com/tag/artificial-intelligence/", "security", "https://blog.trailofbits.com/tag/artificial-intelligence/feed/"),
    NewsSource("Lakera Blog", "https://www.lakera.ai/blog", "security"),
    NewsSource("Protect AI Blog", "https://protectai.com/blog", "security"),
    NewsSource("Credo AI Blog", "https://www.credo.ai/blog", "policy"),
    NewsSource("Mozilla AI", "https://blog.mozilla.org/en/tag/ai/", "policy", "https://blog.mozilla.org/en/tag/ai/feed/"),
    NewsSource("Ada Lovelace Institute AI", "https://www.adalovelaceinstitute.org/topic/artificial-intelligence/", "policy"),
    NewsSource("Stanford AI Index", "https://aiindex.stanford.edu/news/", "policy"),
    NewsSource("RAND AI", "https://www.rand.org/topics/artificial-intelligence.html", "policy"),
    NewsSource("CSET AI", "https://cset.georgetown.edu/topic/artificial-intelligence/", "policy"),
    NewsSource("Tech Policy Press AI", "https://www.techpolicy.press/tag/artificial-intelligence/", "policy", "https://www.techpolicy.press/rss/"),
    NewsSource("AI Incident Database Blog", "https://incidentdatabase.ai/blog/", "policy"),
    NewsSource("MLCommons News", "https://mlcommons.org/news/", "policy"),
)


def sources_by_category(category: str) -> tuple[NewsSource, ...]:
    """Return all configured sources in a category."""

    return tuple(source for source in SOURCES if source.category == category)
